# Generated by Django 2.2.6 on 2020-06-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(verbose_name='CPU Percent')),
                ('user_times', models.IntegerField(verbose_name='User Time')),
                ('temperature', models.IntegerField(verbose_name='CPU Temperature')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.IntegerField(verbose_name='Bytes Sent')),
                ('received', models.IntegerField(verbose_name='Bytes Received')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='Total Ram')),
                ('percent', models.FloatField(verbose_name='RAM Usage')),
            ],
        ),
    ]
